#!/usr/bin/env ruby

require 'active_support/inflector'

# Takes a file path as argument and creates a spec file for RSpec
# Usage:
#
#   spec app/services/hola.rb #=> Generates spec/services/hola_spec.rb with the default RSpec describe block.
#
# VIM usage:
#
#   :!spec %

file_name = ARGV[0]

spec_name = file_name.gsub(/\Aapp/, 'spec')
spec_name = spec_name.gsub(/.rb\z/, '_spec.rb')

class_name = ActiveSupport::Inflector.classify(
  file_name.split('/')[2..-1].join('/').gsub('.rb', '')
)

`touch #{spec_name}`
`echo "require 'rails_helper'\n\nRSpec.describe #{class_name} do\n\nend" > #{spec_name}`
